<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="utf-8">
    <title>@yield('title', 'HENKATEN BOARD') - Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {{-- Security patch 2026-05-10: per-session nonce for browser API clients --}}
    {{-- Generated by GenerateApiNonce middleware; validated by VerifyAppSecret --}}
    <meta name="api-nonce" content="{{ session('api_nonce', '') }}">

    {{-- Fonts --}}
    <link
        href="https://fonts.googleapis.com/css2?family=Orbitron:wght@700;900&family=Rajdhani:wght@500;600;700&family=Exo+2:wght@400;500;600&family=Roboto+Condensed:wght@400;600;700&family=Roboto:wght@300;400;500;700&display=swap"
        rel="stylesheet">

    {{-- Chart.js --}}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>

    {{-- xlsx untuk export Excel di browser --}}
    <script src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js"></script>
    <script src="{{ asset('js/auto-sync.js') }}"></script>

    {{-- CSS utama --}}
    <link rel="stylesheet" href="{{ asset('assets/css/henkaten.css') }}">

    {{-- Dynamic Theme Styles --}}
    @php
        $siteConfigs = \App\Models\SiteConfig::all()->pluck('value', 'key');
        $navbarBg = $siteConfigs['navbar_color'] ?? '#2E7D32';
        $primaryColor = $siteConfigs['primary_color'] ?? '#2E7D32';
        $secondaryColor = $siteConfigs['secondary_color'] ?? '#729E3F';
        $themeEffect = $siteConfigs['theme_effect'] ?? 'normal';

        // Helper to convert hex to RGB for translucent colors
        $hexToRgb = function($hex) {
            $hex = str_replace('#', '', $hex);
            if(strlen($hex) == 3) {
                $r = hexdec(substr($hex,0,1).substr($hex,0,1));
                $g = hexdec(substr($hex,1,1).substr($hex,1,1));
                $b = hexdec(substr($hex,2,1).substr($hex,2,1));
            } else {
                $r = hexdec(substr($hex,0,2));
                $g = hexdec(substr($hex,2,2));
                $b = hexdec(substr($hex,4,2));
            }
            return "$r, $g, $b";
        };
        $primaryRgb = $hexToRgb($primaryColor);

        // Fetch current factory's gradient for Warna Header
        $rawFactory = $factory ?? session('factory') ?? request('factory') ?? 'Factory 2';
        $normalizedName = html_entity_decode($rawFactory, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $factoryData = $factories->firstWhere('name', $normalizedName);
        $factoryGradient = $factoryData?->gradient ?: 'var(--brand-primary)';
    @endphp
    <style>
        :root {
            --navbar-bg: {{ $navbarBg }};
            --brand-primary: {{ $primaryColor }};
            --brand-primary-rgb: {{ $primaryRgb }};
            --brand-secondary: {{ $secondaryColor }};
            --warna-header: {{ $factoryGradient }};
        }

        /* Navbar dynamic colors */
        .app-header.desktop-header { background: var(--navbar-bg) !important; }
        

        /* 1. Dynamic Primary Theme Mapping */
        .statusChip { background: var(--brand-primary) !important; color: #fff !important; }
        .leg-dot[style*="background: #729E3F"], .leg-dot[style*="background:#729E3F"] { background: var(--brand-primary) !important; }
        
        /* Apply Primary Branding Color */
        .date-label, 
        button[onclick*="showFactoryPicker"] {
            background: var(--brand-primary) !important;
            color: #fff !important;
        }

        /* Factory-context items should follow --warna-header */
        .mobile-factory-badge,
        .machine-group-title,
        .shift-toggle-btn.active,
        .dmb-btn.active, 
        .dmb-apply,
        .absenFill { 
            background: var(--brand-primary) !important; 
            color: #fff !important;
        }

        .um-add-btn { background: var(--brand-primary) !important; color: #fff !important; }
        .um-table thead tr { background: var(--brand-primary) !important; color: #fff !important; }
        .um-table tr { border-left: 3px solid transparent; transition: all 0.2s; }
        .um-table tr:hover { background-color: rgba(var(--brand-primary-rgb), 0.05); border-left-color: var(--brand-primary) !important; }

        /* 2. Exception Rules (Warna Header mapping in Modals) */
        .modal-sheet-body .btn-primary,
        .modal-sheet-body .ar-save-btn,
        .modal-sheet-body .um-add-btn,
        .modal-sheet-body .save-btn-big {
            background: var(--warna-header) !important;
            color: #fff !important;
            border: none;
        }

        /* 3. Component-Specific UI Styling (iOS Glassmorphism) */
        .header-menu-btn {
            background: rgba(255, 255, 255, 0.4) !important;
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.5) !important;
            color: #fff !important;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }

        /* Brand primary overrides */
        .btn-primary, .ar-save-btn, .ar-add-btn, .mobile-menu-btn, .save-btn-big {
            background: var(--brand-primary) !important;
        }
        
        .shift-toggle-btn.active { background: var(--brand-primary) !important; }
        .drawer-item.active .di-icon { background: var(--brand-primary) !important; }
        .drawer-header { background: var(--brand-primary) !important; }
        .tv-mode-btn { background: var(--brand-primary) !important; }

        /* Secondary color overrides */
        .mg-badge:not(.warn) { background: var(--brand-secondary) !important; }

        /* Glossy Effect */
        @if($themeEffect === 'glossy')
        .btn-primary, .ar-save-btn, .ar-add-btn, .save-btn-big, .app-header, .bottom-nav, .shift-toggle-btn.active, .tv-mode-btn {
            background-image: linear-gradient(to bottom, rgba(255,255,255,0.2) 0%, rgba(255,255,255,0.05) 50%, rgba(0,0,0,0.05) 100%) !important;
            box-shadow: 0 4px 12px rgba(0,0,0,0.12), inset 0 1px 0 rgba(255,255,255,0.3) !important;
            border: 1px solid rgba(0,0,0,0.1) !important;
        }
        @endif
    </style>

    @stack('styles')
</head>

<body class="{{ $themeEffect === 'glossy' ? 'theme-glossy' : '' }}">

    {{-- ── LOADING OVERLAY ── --}}
    <div class="loading-overlay" id="loadingEl">
        <div class="loading-spinner"></div>
        <div class="loading-text" id="loadingText">Loading...</div>
    </div>

    {{-- ── TOAST ── --}}
    <div class="toast" id="toastEl"></div>

    {{-- ── DRAWER MENU ── --}}
    <div class="drawer-overlay" id="drawerOverlay" onclick="closeDrawer()"></div>
    <div class="drawer-menu" id="drawerMenu">

        {{-- Header --}}
        <div class="drawer-header">
            <div class="dh-logo">HENKATEN BOARD</div>
            <div class="dh-user">{{ auth()->user()->name }} ({{ auth()->user()->role }})</div>
            <button class="drawer-close-btn" onclick="closeDrawer()">
                {{-- Lucide X --}}
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                    stroke="#fff" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
            </button>
        </div>

        {{-- Nav --}}
        <div class="drawer-nav">

            {{-- Dashboard --}}
            <button class="drawer-item {{ request()->routeIs('admin.dashboard') ? 'active' : '' }}"
                onclick="window.location='{{ route('admin.dashboard') }}'">
                <span class="di-icon">
                    {{-- Lucide LayoutDashboard --}}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round">
                        <rect x="3" y="3" width="7" height="7" />
                        <rect x="14" y="3" width="7" height="7" />
                        <rect x="14" y="14" width="7" height="7" />
                        <rect x="3" y="14" width="7" height="7" />
                    </svg>
                </span>
                Dashboard
            </button>

            {{-- TV Mode --}}
            <button class="tv-mode-btn" onclick="toggleTvDropdown()" id="tvDropdownBtn">
                <span class="tv-mode-btn-left">
                    <span class="tv-mode-icon">
                        {{-- Lucide Monitor --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
                            <line x1="8" y1="21" x2="16" y2="21" />
                            <line x1="12" y1="17" x2="12" y2="21" />
                        </svg>
                    </span>
                    <span class="tv-mode-label">Mode TV</span>
                </span>
                <span id="tvChevron">
                    {{-- Lucide ChevronDown --}}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2.5"
                        stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="6 9 12 15 18 9" />
                    </svg>
                </span>
            </button>

            {{-- TV Dropdown - dynamic from DB --}}
            <div id="tvDropdown" style="display:none;">
                @foreach($factories as $fac)
                    @if(auth()->user()->isSuperAdmin() || (is_array(auth()->user()->factory) && in_array($fac->name, auth()->user()->factory)))
                        <div class="tv-factory-block">
                            <div class="tv-factory-header" style="background:{{ $fac->gradient }};">
                                {{-- Lucide Factory --}}
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M2 20V9l7-4v4l7-4v4l4-2v13H2z" />
                                </svg>
                                <span>{{ $fac->name }}</span>
                            </div>
                            <div class="tv-shift-row">
                                <button class="tv-shift-btn" onclick="openTvMode('{{ $fac->name }}','A')"
                                    onmouseover="this.style.background='#e8f5e9'"
                                    onmouseout="this.style.background='transparent'">
                                    <span class="tv-shift-factory-label">{{ $fac->short_label }}</span>
                                    <span class="tv-shift-badge badge-a">SHIFT A</span>
                                </button>
                                <button class="tv-shift-btn" onclick="openTvMode('{{ $fac->name }}','B')"
                                    onmouseover="this.style.background='#ffebee'"
                                    onmouseout="this.style.background='transparent'">
                                    <span class="tv-shift-factory-label">{{ $fac->short_label }}</span>
                                    <span class="tv-shift-badge badge-b">SHIFT B</span>
                                </button>
                            </div>
                        </div>
                    @endif
                @endforeach
            </div>

            <div class="drawer-divider"></div>
            <div class="drawer-section-label">Halaman</div>

            @if(auth()->user()->isSuperAdmin() || auth()->user()->role === 'admin')
                {{-- Member Management --}}
                <button class="drawer-item {{ request()->routeIs('admin.members.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.members.index') }}'">
                    <span class="di-icon">
                        {{-- Lucide Users --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
                            <circle cx="9" cy="7" r="4" />
                            <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
                            <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                        </svg>
                    </span>
                    Member Management
                </button>

                {{-- Mesin Management --}}
                <button class="drawer-item {{ request()->routeIs('admin.mesinmg.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.mesinmg.index') }}'">
                    <span class="di-icon">
                        {{-- Lucide Cog --}}
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="lucide lucide-cog-icon lucide-cog">
                            <path d="M11 10.27 7 3.34" />
                            <path d="m11 13.73-4 6.93" />
                            <path d="M12 22v-2" />
                            <path d="M12 2v2" />
                            <path d="M14 12h8" />
                            <path d="m17 20.66-1-1.73" />
                            <path d="m17 3.34-1 1.73" />
                            <path d="M2 12h2" />
                            <path d="m20.66 17-1.73-1" />
                            <path d="m20.66 7-1.73 1" />
                            <path d="m3.34 17 1.73-1" />
                            <path d="m3.34 7 1.73 1" />
                            <circle cx="12" cy="12" r="2" />
                            <circle cx="12" cy="12" r="8" />
                        </svg>
                    </span>
                    Mesin Management
                </button>
            @endif

            @if(auth()->user()->isSuperAdmin() || auth()->user()->role === 'admin')
                {{-- Konfigurasi: Group / Section / Status --}}
                <div class="drawer-divider"></div>
                <div class="drawer-section-label">Konfigurasi</div>

                @if(auth()->user()->isSuperAdmin())
                    @if(auth()->user()->isSuperAdmin())
                        <button class="drawer-item {{ request()->routeIs('admin.group.*') ? 'active' : '' }}"
                            onclick="window.location='{{ route('admin.group.index') }}'">
                            <span class="di-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <rect x="2" y="7" width="20" height="14" rx="2" />
                                    <path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2" />
                                </svg>
                            </span>
                            Group (Factory)
                        </button>

                        <button class="drawer-item {{ request()->routeIs('admin.absence-reasons.*') ? 'active' : '' }}"
                            onclick="window.location='{{ route('admin.absence-reasons.index') }}'">
                            <span class="di-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                                    <polyline points="14 2 14 8 20 8" />
                                    <line x1="16" y1="13" x2="8" y2="13" />
                                    <line x1="16" y1="17" x2="8" y2="17" />
                                    <polyline points="10 9 9 9 8 9" />
                                </svg>
                            </span>
                            Absence Detail
                        </button>

                        <button class="drawer-item {{ request()->routeIs('admin.site-config.*') ? 'active' : '' }}"
                            onclick="window.location='{{ route('admin.site-config.index') }}'">
                            <span class="di-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>
                                </svg>
                            </span>
                            Site Config
                        </button>                    @endif
                @endif

                <button class="drawer-item {{ request()->routeIs('admin.section.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.section.index') }}'">
                    <span class="di-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <line x1="8" y1="6" x2="21" y2="6" />
                            <line x1="8" y1="12" x2="21" y2="12" />
                            <line x1="8" y1="18" x2="21" y2="18" />
                            <line x1="3" y1="6" x2="3.01" y2="6" />
                            <line x1="3" y1="12" x2="3.01" y2="12" />
                            <line x1="3" y1="18" x2="3.01" y2="18" />
                        </svg>
                    </span>
                    Section Management
                </button>

                <button class="drawer-item {{ request()->routeIs('admin.status.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.status.index') }}'">
                    <span class="di-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <circle cx="12" cy="12" r="10" />
                            <line x1="12" y1="8" x2="12" y2="12" />
                            <line x1="12" y1="16" x2="12.01" y2="16" />
                        </svg>
                    </span>
                    Status Management
                </button>

                <button class="drawer-item {{ request()->routeIs('admin.repair-departments.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.repair-departments.index') }}'">
                    <span class="di-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <rect x="3" y="3" width="7" height="9" />
                            <rect x="14" y="3" width="7" height="5" />
                            <rect x="14" y="12" width="7" height="9" />
                            <rect x="3" y="16" width="7" height="5" />
                        </svg>
                    </span>
                    Departemen Perbaikan
                </button>
            @endif

            {{-- Input Absen --}}
            <button class="drawer-item {{ request()->routeIs('admin.absence.*') ? 'active' : '' }}"
                onclick="window.location='{{ route('admin.absence.index', ['factory' => session('factory', 'Factory 2'), 'shift' => session('shift', 'A')]) }}'">
                <span class="di-icon">
                    {{-- Lucide CheckSquare --}}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round">
                        <polyline points="9 11 12 14 22 4" />
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
                    </svg>
                </span>
                Input Absen
            </button>

            {{-- Laporan --}}
            <button class="drawer-item {{ request()->routeIs('admin.reports.*') ? 'active' : '' }}"
                onclick="window.location='{{ route('admin.reports.index') }}'">
                <span class="di-icon">
                    {{-- Lucide BarChart2 --}}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                        stroke-linecap="round" stroke-linejoin="round">
                        <line x1="18" y1="20" x2="18" y2="10" />
                        <line x1="12" y1="20" x2="12" y2="4" />
                        <line x1="6" y1="20" x2="6" y2="14" />
                    </svg>
                </span>
                Laporan
            </button>

            @if(auth()->user()->isAdmin())
                <div class="drawer-divider"></div>
                <div class="drawer-section-label">Admin</div>

                {{-- User Management --}}
                <button class="drawer-item {{ request()->routeIs('admin.users.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.users.index') }}'">
                    <span class="di-icon">
                        {{-- Lucide ShieldCheck --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                            <polyline points="9 12 11 14 15 10" />
                        </svg>
                    </span>
                    User Management
                </button>
            @endif

            {{-- Task 6: Global Logs — Super Admin Only --}}
            @if(auth()->user()->isSuperAdmin())
                <div class="drawer-divider"></div>
                <div class="drawer-section-label">Super Admin</div>
                
                <button class="drawer-item {{ request()->routeIs('admin.master-data.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.master-data.index') }}'">
                    <span class="di-icon">
                        {{-- Lucide Database --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <ellipse cx="12" cy="5" rx="9" ry="3"></ellipse>
                            <path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"></path>
                            <path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"></path>
                        </svg>
                    </span>
                    Master Data
                </button>

                <button class="drawer-item {{ request()->routeIs('admin.global-logs.*') ? 'active' : '' }}"
                    onclick="window.location='{{ route('admin.global-logs.index') }}'">
                    <span class="di-icon">
                        {{-- Lucide Activity --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
                        </svg>
                    </span>
                    Global Logs
                </button>
            @endif

            <div class="drawer-divider"></div>

            {{-- Logout --}}
            <form method="POST" action="{{ route('logout') }}" style="margin:0">
                @csrf
                <button type="submit" class="drawer-item logout-item" style="width:calc(100% - 24px)">
                    <span class="di-icon">
                        {{-- Lucide LogOut --}}
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke-width="2"
                            stroke-linecap="round" stroke-linejoin="round">
                            <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" />
                            <polyline points="16 17 21 12 16 7" />
                            <line x1="21" y1="12" x2="9" y2="12" />
                        </svg>
                    </span>
                    Keluar dari aplikasi
                </button>
            </form>

        </div>
    </div>

    {{-- ── HEADER (DESKTOP) ── --}}
    <div class="app-header desktop-header" style="padding:0 12px;gap:10px;">
        <button class="header-menu-btn" onclick="openDrawer()">☰</button>

        {{-- Logo Sugity + Nama --}}
        <div style="display:flex;align-items:center;gap:10px;flex:1;min-width:0;">
            <img src="{{ asset('images/sugity.png') }}" alt="Sugity Creatives"
                style="height:36px;width:auto;object-fit:contain;flex-shrink:0;" onerror="this.style.display='none'">
            <div style="display:flex;flex-direction:column;line-height:1.2;min-width:0;">
                <span
                    style="font-family:'Roboto Condensed',sans-serif;font-weight:900;font-size:16px;letter-spacing:2px;color:#f5a623;text-shadow:0 0 14px rgba(245,166,35,.5);white-space:nowrap;">HENKATEN
                    BOARD</span>
                <span
                    style="font-family:'Roboto Condensed',sans-serif;font-weight:700;font-size:11px;letter-spacing:1.2px;color:rgba(255,255,255,.85);text-transform:uppercase;white-space:nowrap;">
                    {{ session('factory', 'Factory 2') }}
                </span>
            </div>
        </div>

        <div class="header-clock" id="headerClock">00:00:00</div>

        {{-- Factory switcher - tombol pill keren --}}
        <button onclick="showFactoryPicker()" id="headerFactory" style="background:rgba(255,255,255,.12);
                   border:1.5px solid rgba(255,255,255,.25);
                   border-radius:20px;
                   padding:5px 14px;
                   color:#fff;
                   font-family:'Roboto Condensed',sans-serif;
                   font-weight:700;
                   font-size:11px;
                   letter-spacing:.8px;
                   cursor:pointer;
                   display:flex;
                   align-items:center;
                   gap:5px;
                   white-space:nowrap;
                   transition:all .2s ease;" onmouseover="
                this.style.background='linear-gradient(135deg,rgba(255,255,255,0.35) 0%,rgba(255,255,255,0.10) 50%,rgba(255,255,255,0.20) 100%)';
                this.style.backdropFilter='blur(12px) saturate(1.8)';
                this.style.webkitBackdropFilter='blur(12px) saturate(1.8)';
                this.style.boxShadow='0 4px 16px rgba(0,0,0,0.18),inset 0 1px 0 rgba(255,255,255,0.5)';
                this.style.borderColor='rgba(255,255,255,0.45)';" onmouseout="
                this.style.background='rgba(255,255,255,.12)';
                this.style.backdropFilter='none';
                this.style.webkitBackdropFilter='none';
                this.style.boxShadow='none';
                this.style.borderColor='rgba(255,255,255,.25)';">
            @php
                $__sessionF = session('factory', 'Factory 2');
                $__headerShort = $factories->firstWhere('name', $__sessionF)?->short_label ?? $__sessionF;
            @endphp
            {{ $__headerShort }}
        </button>

        {{-- User info --}}
        <div style="display:flex;align-items:center;gap:10px;margin-left:8px;">
            <div style="text-align:right;line-height:1.2;">
                <div
                    style="color:#fff;font-family:'Roboto Condensed',sans-serif;font-weight:700;font-size:13px;letter-spacing:.4px;">
                    {{ Auth::user()->name ?? 'Admin User' }}
                </div>
                <div style="color:rgba(255,255,255,.65);font-size:10px;letter-spacing:.5px;">
                    {{ Auth::user()->role_label ?? Auth::user()->role ?? 'Administrator' }}
                </div>
            </div>
            <div
                style="width:36px;height:36px;border-radius:50%;background:linear-gradient(135deg,#f5a623,#e67e22);border:2px solid rgba(255,255,255,.35);flex-shrink:0;display:flex;align-items:center;justify-content:center;font-family:'Roboto Condensed',sans-serif;font-weight:900;font-size:14px;color:#fff;letter-spacing:.5px;">
                {{ strtoupper(substr(Auth::user()->name ?? 'A', 0, 1)) }}
            </div>
        </div>
    </div>

    {{-- ── HEADER (MOBILE) ── --}}
    <div class="app-header mobile-header">
        <button class="mobile-menu-btn" onclick="openDrawer()">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2"
                stroke-linecap="round" stroke-linejoin="round">
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
            </svg>
        </button>

        <div class="mobile-brand-container">
            <img class="mobile-logo-svg" src="{{ asset('images/sugity.png') }}" alt="S"
                onerror="this.style.display='none'">
            <div class="mobile-brand-text">
                <span class="mb-title">HENKATEN BOARD</span>
                <span class="mb-subtitle">
                    {{ strtoupper(session('factory', 'Factory 2')) }}
                </span>
            </div>
        </div>

        <button class="mobile-factory-badge" onclick="showFactoryPicker()">
            {{ $factories->firstWhere('name', session('factory', 'Factory 2'))?->short_label ?? session('factory', 'Factory 2') }}
        </button>
    </div>


    {{-- ── MAIN CONTENT ── --}}
    <div class="main-content">
        @yield('content')
    </div>

    {{-- ── BOTTOM NAV ── --}}
    @php
        $currentFactory = session('factory', 'Factory 2');
        $currentShift = session('shift', 'A');
        $absenUrl = route('admin.absence.index', ['factory' => $currentFactory, 'shift' => $currentShift]);
    @endphp

    <nav class="bottom-nav">

        {{-- Dashboard --}}
        <button class="nav-btn {{ request()->routeIs('admin.dashboard') ? 'active' : '' }}"
            onclick="window.location='{{ route('admin.dashboard') }}'">
            <span class="nav-icon">
                {{-- Lucide House --}}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M3 9.5L12 3l9 6.5V20a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9.5z" />
                    <polyline points="9 21 9 12 15 12 15 21" />
                </svg>
            </span>
            Dashboard
        </button>

        {{-- Absen --}}
        <button
            class="nav-btn {{ request()->routeIs('admin.absence.*', 'admin.members.*', 'admin.attendance.*') ? 'active' : '' }}"
            onclick="window.location='{{ $absenUrl }}'">
            <span class="nav-icon">
                {{-- Lucide CheckSquare --}}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <polyline points="9 11 12 14 22 4" />
                    <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
                </svg>
            </span>
            Absen
        </button>

        {{-- Laporan --}}
        <button class="nav-btn {{ request()->routeIs('admin.reports.*') ? 'active' : '' }}"
            onclick="window.location='{{ route('admin.reports.index') }}'">
            <span class="nav-icon">
                {{-- Lucide BarChart2 --}}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <line x1="18" y1="20" x2="18" y2="10" />
                    <line x1="12" y1="20" x2="12" y2="4" />
                    <line x1="6" y1="20" x2="6" y2="14" />
                </svg>
            </span>
            History 4M
        </button>

    </nav>

    {{-- ── FACTORY PICKER MODAL - dynamic from DB ── --}}
     <div class="modal-overlay" id="factorySheet">
        <div class="modal-sheet">
            <div class="modal-sheet-handle"></div>
            <div class="modal-sheet-header">
                <h3>Pilih Factory</h3>
                <button class="modal-sheet-close" onclick="closeSheet('factorySheet')">✕</button>
            </div>
            <div class="modal-sheet-body">
                <div style="display:flex;flex-direction:column;gap:12px">
                    @php $userRole = auth()->user()->role;
                    $userFactory = auth()->user()->factory; @endphp
                    @foreach($factories as $fac)
                        @if($userRole === 'admin' || !$userFactory || $userFactory === $fac->name)
                            <button class="btn-primary" style="background:{{ $fac->gradient }} !important; border: none;"
                                onclick="setFactory('{{ addslashes($fac->name) }}')">🏭 {{ $fac->name }}</button>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    {{-- ── TV PICKER SHEET (dari bottom nav) - dynamic from DB ── --}}
    <div class="modal-overlay" id="tvPickerSheet">
        <div class="modal-sheet">
            <div class="modal-sheet-handle"></div>
            <div class="modal-sheet-header">
                <h3>📺 Buka TV Mode</h3>
                <button class="modal-sheet-close" onclick="closeSheet('tvPickerSheet')">✕</button>
            </div>
            <div class="modal-sheet-body" style="padding:8px 14px 20px;">
                <div style="display:flex;flex-direction:column;gap:12px;">
                    @foreach($factories as $fac)
                        <div style="border-radius:14px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.12);">
                            {{-- Header factory --}}
                            <div style="background:{{ $fac->gradient }};padding:10px 16px;
                                                    display:flex;align-items:center;gap:8px;">
                                <span style="font-size:18px;">🏭</span>
                                <span style="font-family:'Roboto Condensed',sans-serif;font-weight:900;
                                                         font-size:12px;letter-spacing:1.5px;color:#fff;
                                                         text-transform:uppercase;">{{ $fac->name }}</span>
                            </div>
                            {{-- Shift buttons --}}
                            @php 
                                $warna_header = $fac->gradient ?: 'var(--brand-primary)'; 
                                preg_match('/#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})/', $warna_header, $matches);
                                $baseTint = $matches[0] ?? '#2E7D32';
                                $hoverTint = $baseTint . '1a'; // ~10% opacity hex
                            @endphp
                            <div style="display:flex;background:#f8f9fa;border:1px solid #e0e0e0;
                                                    border-top:none;border-radius:0 0 14px 14px;overflow:hidden;">
                                <button onclick="openTvMode('{{ $fac->name }}','A');closeSheet('tvPickerSheet')" style="flex:1;padding:14px 8px;border:none;border-right:1px solid #e0e0e0;
                                                           background:transparent;cursor:pointer;transition:background .15s;
                                                           display:flex;flex-direction:column;align-items:center;gap:4px;"
                                    onmouseover="this.style.background='{{ $hoverTint }}'"
                                    onmouseout="this.style.background='transparent'">
                                    <span style="font-family:'Roboto Condensed',sans-serif;font-weight:900;
                                                             font-size:16px;color:#333;">{{ $fac->short_label }}</span>
                                    <span
                                        style="font-family:'Roboto Condensed',sans-serif;font-weight:800;
                                                             font-size:10px;letter-spacing:1px;text-transform:uppercase;
                                                             color:#fff;background:{{ $warna_header }};padding:2px 10px;border-radius:20px;">
                                        SHIFT A
                                    </span>
                                </button>
                                <button onclick="openTvMode('{{ $fac->name }}','B');closeSheet('tvPickerSheet')" style="flex:1;padding:14px 8px;border:none;
                                                           background:transparent;cursor:pointer;transition:background .15s;
                                                           display:flex;flex-direction:column;align-items:center;gap:4px;"
                                    onmouseover="this.style.background='{{ $hoverTint }}'"
                                    onmouseout="this.style.background='transparent'">
                                    <span style="font-family:'Roboto Condensed',sans-serif;font-weight:900;
                                                             font-size:16px;color:#333;">{{ $fac->short_label }}</span>
                                    <span
                                        style="font-family:'Roboto Condensed',sans-serif;font-weight:800;
                                                             font-size:10px;letter-spacing:1px;text-transform:uppercase;
                                                             color:#fff;background:{{ $warna_header }};padding:2px 10px;border-radius:20px;">
                                        SHIFT B
                                    </span>
                                </button>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    {{-- ── SHARED JS ── --}}
    <script>
        const CSRF_TOKEN = document.querySelector('meta[name="csrf-token"]').content;
        const CURRENT_FACTORY = @json(session('factory', 'Factory 2'));
        const CURRENT_SHIFT = @json(session('shift', 'A'));

        // ── Security patch 2026-05-10 ────────────────────────────────────────────
        // API_NONCE: per-session nonce for authenticating browser→/api/* requests.
        // Read from <meta name="api-nonce"> injected by GenerateApiNonce middleware.
        // Sent as X-App-Secret header on every apiFetch() call.
        // This is NOT the raw APP_API_SECRET  - it is a session-bound nonce that
        // expires when the session expires. Safe to embed in page HTML.
        const API_NONCE = document.querySelector('meta[name="api-nonce"]')?.content ?? '';

        /**
         * apiFetch(url, method, body)  - Secure API helper for /api/* routes
         *
         * Automatically adds:
         *   Content-Type: application/json
         *   X-CSRF-TOKEN: (from csrf-token meta)
         *   X-App-Secret: (from api-nonce meta  - session nonce for VerifyAppSecret)
         *   Accept: application/json
         *
         * Throws an Error on non-2xx responses.
         */
        async function apiFetch(url, method = 'GET', body = null) {
            const opts = {
                method,
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': CSRF_TOKEN,
                    'X-App-Secret': API_NONCE,
                    'Accept': 'application/json',
                },
            };
            if (body) opts.body = JSON.stringify(body);
            const res = await fetch(url, opts);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            return res.json();
        }

        /**
         * api()  - Legacy helper (kept for backward compat with existing Blade code)
         * @deprecated Use apiFetch() for new code targeting /api/* routes.
         *             This wrapper still works for old /admin/* JSON routes.
         */
        async function api(url, method = 'GET', body = null) {
            const opts = {
                method,
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': CSRF_TOKEN,
                    'X-App-Secret': API_NONCE,
                    'Accept': 'application/json',
                },
            };
            if (body) opts.body = JSON.stringify(body);
            const res = await fetch(url, opts);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            return res.json();
        }

        function updateClock() {
            document.getElementById('headerClock').textContent =
                new Date().toLocaleTimeString('en-GB', { hour12: false });
        }
        setInterval(updateClock, 1000);
        updateClock();

        function showToast(msg, type = 'info') {
            const t = document.getElementById('toastEl');
            t.textContent = msg;
            t.className = `toast ${type} show`;
            clearTimeout(t._timer);
            t._timer = setTimeout(() => t.classList.remove('show'), 2800);
        }

        function showLoading(msg) {
            document.getElementById('loadingEl').classList.add('show');
            document.getElementById('loadingText').textContent = msg || 'Loading...';
        }
        function hideLoading() { document.getElementById('loadingEl').classList.remove('show'); }

        function openDrawer() { document.getElementById('drawerMenu').classList.add('open'); document.getElementById('drawerOverlay').classList.add('show'); }
        function closeDrawer() { document.getElementById('drawerMenu').classList.remove('open'); document.getElementById('drawerOverlay').classList.remove('show'); }

        function openSheet(id) { document.getElementById(id).classList.add('show'); }
        function closeSheet(id) { document.getElementById(id).classList.remove('show'); }
        function showFactoryPicker() { openSheet('factorySheet'); }

        async function setFactory(factory) {
            await api('{{ route('admin.context') }}', 'POST', { factory, shift: CURRENT_SHIFT });
            const cur = window.location.pathname;
            if (cur.includes('/absence')) {
                const params = new URLSearchParams(window.location.search);
                params.set('factory', factory);
                params.set('shift', CURRENT_SHIFT);
                window.location.href = '{{ route('admin.absence.index') }}?' + params.toString();
            } else {
                window.location.reload();
            }
        }

        async function switchShift(shift) {
            await api('{{ route('admin.context') }}', 'POST', { factory: CURRENT_FACTORY, shift });
            const cur = window.location.pathname;
            if (cur.includes('/absence')) {
                const params = new URLSearchParams(window.location.search);
                params.set('factory', CURRENT_FACTORY);
                params.set('shift', shift);
                window.location.href = '{{ route('admin.absence.index') }}?' + params.toString();
            } else {
                window.location.reload();
            }
        }

        function toggleTvBottomSheet() { openSheet('tvPickerSheet'); }

        function toggleTvDropdown() {
            const dd = document.getElementById('tvDropdown');
            const chv = document.getElementById('tvChevron');
            const open = dd.style.display === 'none';
            dd.style.display = open ? 'block' : 'none';
            chv.style.transform = open ? 'rotate(180deg)' : 'rotate(0deg)';
        }

        function openTvMode(factory, shift) {
            // Buka TV Mode langsung dengan factory & shift di query string
            // Tidak mengubah session global  - TV page baca dari ?factory=...&shift=...
            const url = '{{ route('admin.tv') }}?factory=' + encodeURIComponent(factory) + '&shift=' + encodeURIComponent(shift);
            window.open(url, '_blank');
        }

        let touchStartX = 0, touchStartY = 0;
        document.addEventListener('touchstart', e => {
            touchStartX = e.touches[0].clientX;
            touchStartY = e.touches[0].clientY;
        }, { passive: true });
        document.addEventListener('touchend', e => {
            const dx = e.changedTouches[0].clientX - touchStartX;
            const dy = e.changedTouches[0].clientY - touchStartY;
            if (Math.abs(dx) > 60 && Math.abs(dy) < 40) {
                if (dx > 0 && touchStartX < 40) openDrawer();
                else if (dx < 0) closeDrawer();
            }
        }, { passive: true });
    </script>

    @stack('scripts')
</body>

</html>